apiVersion: v1
kind: Namespace
metadata:
  name: thalamus
  labels:
    app.kubernetes.io/part-of: thalamus
    environment: production
    istio.io/dataplane-mode: ambient
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
